// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wttdczmnrgylwulhtcji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0dGRjem1ucmd5bHd1bGh0Y2ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzE2MDMsImV4cCI6MjA3MzUwNzYwM30.JGR5IcrzQFu-iecPjo2oK9Jzr3cyslP8kNDSYd4dT3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});